# Generated by Django 4.2.7 on 2025-08-13 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequirementcheck',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyrequirementcheck',
            name='property_compliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_checks', to='compliance.propertycompliance'),
        ),
        migrations.AddField(
            model_name='propertyrequirementcheck',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancerequirement'),
        ),
        migrations.AddField(
            model_name='propertycompliance',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertycompliance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='propertyrequirementcheck',
            unique_together={('property_compliance', 'requirement')},
        ),
    ]
